name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: C/C++ Lint Action
        uses: shenxianpeng/cpp-linter-action@v1.3.0
        with:
          thread-comments: true
          style: c,h
          extensions: c,h
          tidy-checks: boost-*,bugprone-*,performance-*,readability-*,portability-*,modernize-*,clang-analyzer-*,cppcoreguidelines-*
          repo-root: src
          version: 10
          verbosity: 10
          lines-changed-only: false
          files-changed-only: false
          ignore: .github
